- run: echo "Test"

deploy-dev:
  needs: test
  if: github.ref_name == 'develop'
  uses: ./.github/workflows/deploy.yml
  with:
    environment: dev

deploy-staging:
  needs: test
  if: github.ref_name == 'staging'
  uses: ./.github/workflows/deploy.yml
  with:
    environment: staging

deploy-prod:
  needs: test
  if: github.ref_name == 'main'
  uses: ./.github/workflows/deploy.yml
  with:
    environment: prod
